# Site settings
title: For Human Sake
tagline: Mental Health for Software Developers and Online Workers
url: "https://teameverybody.org" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /images/og.png

# Contact
email: "patrick.lorenzut@gmail.com"

# Use this for production
sass:
  sass_dir: css
  style: compressed

collections:
  - thoughts
  - transformation